---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: version-reader
  namespace: system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["oneinfra-version"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: version-reader
  namespace: system
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
roleRef:
  kind: Role
  name: version-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: version-updater
  namespace: system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["oneinfra-version"]
  verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: version-updater
  namespace: system
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
roleRef:
  kind: Role
  name: version-updater
  apiGroup: rbac.authorization.k8s.io
