apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../config/crd
- ../../config/webhook
patchesStrategicMerge:
- runtime-patches/mutating_webhook_configuration.yaml
- runtime-patches/validating_webhook_configuration.yaml
resources:
- resources/system-namespace.yaml
- resources/oneinfra-system-namespace.yaml
